image: docker:latest

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "your-docker-image-name"
  IMAGE_TAG: "latest"
  REGISTRY: "registry.gitlab.com/your-namespace/your-project"
  DEPLOY_SERVER: "your-server-ip"
  DEPLOY_USER: "your-user"
  DEPLOY_PATH: "/var/www/your-app"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $REGISTRY

build:
  stage: build
  script:
    - docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "
        docker pull $REGISTRY/$IMAGE_NAME:$IMAGE_TAG &&
        docker stop $IMAGE_NAME || true &&
        docker rm $IMAGE_NAME || true &&
        docker run -d --name $IMAGE_NAME -p 80:80 $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      "
  only:
    - main
  environment:
    name: production
    url: https://your-deployed-app.com
