image: docker:20.10.16

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "workshop-3-prod" 
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: react-app
  ECR_REGISTRY: 168544657306.dkr.ecr.eu-north-1.amazonaws.com
  IMAGE_URI: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

before_script:
  # Configure AWS CLI
  - apk add --no-cache python3 py3-pip
  - pip3 install --no-cache-dir awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_REGION

build:
  stage: build
  script:
    # Authenticate Docker to AWS ECR
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    # Build Docker image
    - docker build -t $IMAGE_URI .
    # Push Docker image to AWS ECR
    - docker push $IMAGE_URI
  only:
    - main
  tags:
    - hva

deploy:
  stage: deploy
  image: amazon/aws-cli:2.15.0
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    - echo "Updating ECS service..."
    - aws ecs update-service \
        --cluster react-cluster1 \
        --service react-service \
        --force-new-deployment
  only:
    - main
  tags:
    - hva
