image: docker:latest

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "workshop-3-prod" 
  IMAGE_TAG: "latest"
  REGISTRY: "gitlab.fdmci.hva.nl:5050/se-specialization-2024-2/tse1/jesse-slijkerman/workshop-3-cicd"
  DEPLOY_SERVER: "your-server-ip"
  DEPLOY_USER: "slijkej2"
  DEPLOY_PATH: "oege.ie.hva.nl"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $REGISTRY 

build:
  stage: build
  script:
    - docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  only:
    - main
  tags:
    - hva

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "
        docker pull $REGISTRY/$IMAGE_NAME:$IMAGE_TAG &&
        docker stop $IMAGE_NAME || true &&
        docker rm $IMAGE_NAME || true &&
        docker run -d --name $IMAGE_NAME -p 8009:8009 $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      "
  only:
    - main 
  environment:
    name: production
    url: https://your-deployed-app.com
  tags:
    - hva  
