image: amazon/aws-cli:2.15.0

stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: react-app
  CODEBUILD_PROJECT: react-app-build
  ECS_CLUSTER: react-cluster1
  ECS_SERVICE: react-service

before_script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_REGION

# 1. Trigger AWS CodeBuild to build and push the Docker image
build:
  stage: build
  tags:
    - hva
  script:
    - echo "Starting AWS CodeBuild project..."
    - aws codebuild start-build --project-name $CODEBUILD_PROJECT \
        --environment-variables-override name=IMAGE_TAG,value=$IMAGE_TAG,type=PLAINTEXT
  only:
    - main

# 2. Deploy the new image to ECS
deploy:
  stage: deploy
  tags:
    - hva
  script:
    - echo "Updating ECS service to use the new image..."
    - aws ecs update-service \
        --cluster $ECS_CLUSTER \
        --service $ECS_SERVICE \
        --force-new-deployment
  only:
    - main
