stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "workshop-3-prod"
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  AWS_REGION: "eu-north-1"
  ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  IMAGE_URI: "$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"

# Build with Kaniko
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    # Authenticate with ECR
    - echo "{\"credHelpers\":{\"$ECR_REGISTRY\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    # Build & push
    - /kaniko/executor --dockerfile $CI_PROJECT_DIR/Dockerfile --context $CI_PROJECT_DIR --destination $IMAGE_URI
  only:
    - main
  tags:
    - hva

# Deploy to ECS
deploy:
  stage: deploy
  image: amazon/aws-cli:2.15.0
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    # Update ECS service to new image
    - aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
  only:
    - main
  environment:
    name: production
    url: https://your-app.aws-region.elb.amazonaws.com
  tags:
    - hva
